### ISSUE TITLE
Need Help About Compiling

### ISSUE THREAD

**Issue by pofdzm** [nikisalli/esp32-minecraft-client#23]
Your client sounds very cool and I would like to test it, but I don't really know how to compile it, like I have 0 knowledge about compiling. I use elementary OS 5.1.7 Hera (ubuntu 18.04 based). Can you a bit explain it?

**Comment by nikisalli** [comment]
just create your own config (to connect to wifi etc.) and compile using platformio https://docs.platformio.org/en/latest/core/quickstart.html
